function xc = centroidx(weight, bar, headNeck, trunk, thigh, shank, ...
             upperArm, shoulder, foreArm, hand, hip, knee, ankle, elbow, i)

if nargin==14; i = length(knee.x); end

headNeckLx = cosd(trunk.a(i))*headNeck.L; % 头颈长度在 x 方向上的投影

% 对(0,0) 的矩
Moment = bar.x(i) * bar.wt + hand.x(i)*hand.wt + ...
    (shoulder.x(i) +headNeck.CoG*headNeckLx                ) * headNeck.wt + ...
    (     hip.x(i) +   trunk.CoG*(shoulder.x(i)-     hip.x(i))) * trunk.wt + ...
    (     hip.x(i) +   thigh.CoG*(    knee.x(i)-     hip.x(i))) * thigh.wt + ...
    (    knee.x(i) +   shank.CoG*(   ankle.x   -    knee.x(i))) * shank.wt + ...
    (shoulder.x(i) +upperArm.CoG*(   elbow.x(i)-shoulder.x(i))) * upperArm.wt + ...
    (   elbow.x(i) + foreArm.CoG*(    hand.x(i)-   elbow.x(i))) * foreArm.wt;

xc = Moment/(weight+bar.wt);